"""
Philippine provinces and cities for the report form, from the PSGC.

The Philippine Standard Geographic Code is published by the Philippine
Statistics Authority (PSA) as an Excel "Publication Datafile", updated
quarterly. This script turns one of those files into the reference rows the
database holds, in two steps, so that the step that needs the 3 MB workbook is
separate from the step everybody else runs:

    python scripts/psgc_reference.py extract <PSGC Publication Datafile.xlsx>
        reads the PSA workbook and writes
        database/reference/ph-provinces.csv and database/reference/ph-cities.csv

    python scripts/psgc_reference.py sql
        writes the INSERTs generated from those two CSVs into schema.sql and
        migration 009, between their BEGIN/END PSGC markers

    python scripts/psgc_reference.py check
        exits non-zero if the CSVs and the two SQL blocks disagree, or if the
        counts are not the ones PSA's own National Summary states

TRANSFORMATION (what is changed between PSA's file and these rows)

  * Only rows whose Geographic Level is Prov, City or Mun are used. Regions,
    barangays and Manila's 14 sub-municipalities (Binondo, Tondo, ...) are not
    a choice on the form: the sub-municipalities are districts of the City of
    Manila, not municipalities (PSA's own note 1).
  * Names are PSA's, with surrounding spaces removed and runs of spaces made
    one. Nothing else: "City of Cebu" stays "City of Cebu".
  * Every city and municipality gets the province it is in:
      - from its own 10-digit code when that names a province (1,599 rows);
      - for a highly urbanized city, which PSA codes as independent of any
        province, from its Correspondence Code, the 9-digit code PSA used
        before 2023, whose first four digits name the province it is in
        ("City of Cebu" 072217000 -> Cebu 0722);
      - Metro Manila: the 16 cities and Pateros are in a region with no
        provinces at all. They are filed under one entry, "Metro Manila",
        with PSA's own NCR code 1300000000;
      - the City of Isabela, under Basilan, per PSA's note 2 ("geographically
        located within the island province of Basilan");
      - the eight municipalities of the Special Geographic Area of BARMM,
        under one entry with PSA's own code for that area, 1999900000.
  * The column `rule` in ph-cities.csv records which of these applied, so
    every row can be traced.
"""

import csv
import hashlib
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF = ROOT / 'database' / 'reference'
PROVINCES_CSV = REF / 'ph-provinces.csv'
CITIES_CSV = REF / 'ph-cities.csv'
SCHEMA = ROOT / 'database' / 'schema.sql'
MIGRATION = ROOT / 'database' / 'migrations' / '009_report_reference_data.sql'

BEGIN = '-- BEGIN PSGC DATA (generated by scripts/psgc_reference.py; do not edit by hand)'
END = '-- END PSGC DATA'

NCR = ('1300000000', 'Metro Manila')
SGA = ('1999900000', 'Special Geographic Area (BARMM)')

# What PSA's National Summary sheet says for the publication used, and what
# the transformation must therefore produce. 82 provinces plus the two
# entries above; every city and every municipality, each exactly once.
EXPECTED = {'provinces': 84, 'cities': 149, 'municipalities': 1493}


def clean(name):
    return re.sub(r'\s+', ' ', str(name)).strip()


def extract(xlsx_path):
    import openpyxl  # only this step needs it

    path = Path(xlsx_path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    book = openpyxl.load_workbook(path, read_only=True)

    published = None
    for row in book['Metadata'].iter_rows(values_only=True):
        if row[0] == 'Publication date:':
            published = row[1]

    rows = [r for r in book['PSGC'].iter_rows(min_row=2, values_only=True) if r[0]]

    def correspondence(row):
        return str(row[2]).zfill(9) if row[2] not in (None, '') else None

    provinces = {str(r[0]): clean(r[1]) for r in rows if r[3] == 'Prov'}
    by_new_prefix = {code[:5]: code for code in provinces}
    by_old_prefix = {
        correspondence(r)[:4]: str(r[0]) for r in rows if r[3] == 'Prov' and correspondence(r)
    }
    basilan = next(code for code, name in provinces.items() if name == 'Basilan')

    cities = []
    for r in rows:
        if r[3] not in ('City', 'Mun'):
            continue
        code = str(r[0])
        old = correspondence(r)
        if code.startswith('13'):
            parent, rule = NCR[0], 'ncr'
        elif code.startswith('19999'):
            parent, rule = SGA[0], 'sga'
        elif code[:5] in by_new_prefix:
            parent, rule = by_new_prefix[code[:5]], 'code'
        elif old and old[:4] == '0997':
            parent, rule = basilan, 'psa-note-isabela'
        elif old and old[:4] in by_old_prefix:
            parent, rule = by_old_prefix[old[:4]], 'correspondence'
        else:
            raise SystemExit(f'No province for {code} {r[1]!r}: add a rule, do not guess')
        cities.append({
            'city_code': code,
            'city_name': clean(r[1]),
            'is_city': 1 if r[3] == 'City' else 0,
            'city_class': r[5] or '',
            'province_code': parent,
            'rule': rule,
        })

    provinces[NCR[0]] = NCR[1]
    provinces[SGA[0]] = SGA[1]

    REF.mkdir(parents=True, exist_ok=True)
    note = f'# PSA PSGC Publication Datafile, publication date {published}; sha256 {digest}\n'
    with PROVINCES_CSV.open('w', encoding='utf-8', newline='') as out:
        out.write(note)
        writer = csv.writer(out, lineterminator='\n')
        writer.writerow(['province_code', 'province_name'])
        for code, name in sorted(provinces.items(), key=lambda item: item[1]):
            writer.writerow([code, name])
    with CITIES_CSV.open('w', encoding='utf-8', newline='') as out:
        out.write(note)
        writer = csv.DictWriter(out, fieldnames=list(cities[0]), lineterminator='\n')
        writer.writeheader()
        for city in sorted(cities, key=lambda c: c['city_code']):
            writer.writerow(city)

    print(f'{len(provinces)} provinces, {len(cities)} cities and municipalities')
    print(f'publication date {published}, sha256 {digest}')


def read_csv(path):
    with path.open(encoding='utf-8') as source:
        lines = [line for line in source if not line.startswith('#')]
    return list(csv.DictReader(io.StringIO(''.join(lines))))


def sql_string(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "''") + "'"


def sql_block():
    provinces = read_csv(PROVINCES_CSV)
    cities = read_csv(CITIES_CSV)
    with PROVINCES_CSV.open(encoding='utf-8') as source:
        provenance = source.readline().lstrip('# ').strip()

    lines = [BEGIN, f'-- Source: {provenance}', '-- Transformation: see scripts/psgc_reference.py.', '']
    lines.append('INSERT IGNORE INTO ph_provinces (province_code, province_name) VALUES')
    lines.append(',\n'.join(
        f"  ({sql_string(p['province_code'])}, {sql_string(p['province_name'])})" for p in provinces
    ) + ';')
    lines.append('')
    # In chunks, so no single statement is enormous.
    for start in range(0, len(cities), 250):
        lines.append('INSERT IGNORE INTO ph_cities (city_code, province_code, city_name, is_city) VALUES')
        lines.append(',\n'.join(
            f"  ({sql_string(c['city_code'])}, {sql_string(c['province_code'])}, "
            f"{sql_string(c['city_name'])}, {c['is_city']})"
            for c in cities[start:start + 250]
        ) + ';')
        lines.append('')
    lines.append(END)
    return '\n'.join(lines)


def replace_block(path, block):
    raw = path.read_bytes()
    crlf = b'\r\n' in raw
    text = raw.decode('utf-8').replace('\r\n', '\n')
    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f'{path.name}: the BEGIN/END PSGC markers are missing')
    text = pattern.sub(lambda _: block, text)
    if crlf:
        text = text.replace('\n', '\r\n')
    path.write_bytes(text.encode('utf-8'))


def current_block(path):
    text = path.read_text(encoding='utf-8').replace('\r\n', '\n')
    match = re.search(re.escape(BEGIN) + r'.*?' + re.escape(END), text, re.S)
    return match.group(0) if match else None


def check():
    provinces = read_csv(PROVINCES_CSV)
    cities = read_csv(CITIES_CSV)
    problems = []
    if len(provinces) != EXPECTED['provinces']:
        problems.append(f"{len(provinces)} provinces, expected {EXPECTED['provinces']}")
    for kind, flag in (('cities', '1'), ('municipalities', '0')):
        count = sum(1 for c in cities if c['is_city'] == flag)
        if count != EXPECTED[kind]:
            problems.append(f'{count} {kind}, expected {EXPECTED[kind]}')
    codes = {p['province_code'] for p in provinces}
    orphans = [c['city_code'] for c in cities if c['province_code'] not in codes]
    if orphans:
        problems.append(f'cities with no province row: {orphans[:5]}')
    seen = set()
    for c in cities:
        key = (c['province_code'], c['city_name'].lower())
        if key in seen:
            problems.append(f'duplicate name in one province: {c["city_name"]}')
        seen.add(key)
    expected = sql_block()
    for path in (SCHEMA, MIGRATION):
        if current_block(path) != expected:
            problems.append(f'{path.name} is out of date: run "python scripts/psgc_reference.py sql"')
    for problem in problems:
        print('FAIL', problem)
    if not problems:
        print(f'ok: {len(provinces)} provinces, {len(cities)} cities and municipalities, '
              'schema.sql and 009 in step')
    return 1 if problems else 0


if __name__ == '__main__':
    command = sys.argv[1] if len(sys.argv) > 1 else ''
    if command == 'extract' and len(sys.argv) == 3:
        extract(sys.argv[2])
    elif command == 'sql':
        block = sql_block()
        replace_block(SCHEMA, block)
        replace_block(MIGRATION, block)
        print('schema.sql and 009 updated')
    elif command == 'check':
        sys.exit(check())
    else:
        print(__doc__)
        sys.exit(2)
