/**
 * Railway-safe copies of schema.sql and seed.sql.
 *
 * Both files open by creating `pawsandfound` and selecting it. A managed host
 * hands you a database that already exists, with a name it chose — Railway's
 * is `railway` — and the account it gives you usually cannot create another
 * one. Running the files unedited either fails on the CREATE or, worse,
 * succeeds and puts every table in a second database the application is not
 * pointed at.
 *
 * So this writes copies with those two statements removed, to be imported
 * against an already-selected database. Nothing else is touched: no table is
 * renamed, no row is changed. Run it, import the output, throw the output
 * away.
 *
 * The output is gitignored on purpose. Two files that both claim to be the
 * schema is how they drift apart — schema.sql stays the only one, and these
 * are regenerated from it whenever they are needed.
 *
 *     node scripts/railway-sql.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const project = dirname(dirname(fileURLToPath(import.meta.url)))
const outputDir = join(project, 'database', 'railway')

// Matches `CREATE DATABASE ... ;` across the lines it is written over, and the
// `USE ...;` that follows it. Anchored to the start of a line so a mention
// inside a comment is left alone. `\r?` because a Windows checkout can hand
// these files over with CRLF line endings (git's autocrlf does exactly that on
// `git restore`), and a pattern that only knew `\n` let the USE line survive.
const CREATE_DATABASE = /^CREATE DATABASE[^;]*;\r?\n/m
const USE_DATABASE = /^USE [^;]*;\r?\n/m

const header = (source) =>
  `-- Generated by scripts/railway-sql.mjs from database/${source}.\n` +
  `-- CREATE DATABASE and USE removed: import this against a database that\n` +
  `-- already exists and is already selected. Do not commit this file; edit\n` +
  `-- database/${source} and regenerate.\n\n`

mkdirSync(outputDir, { recursive: true })

for (const source of ['schema.sql', 'seed.sql']) {
  const original = readFileSync(join(project, 'database', source), 'utf8')
  let text = original

  for (const pattern of [CREATE_DATABASE, USE_DATABASE]) {
    text = text.replace(pattern, '')
  }

  // A silent no-op here would produce a file that looks right and still
  // creates the wrong database, which is the whole failure this exists to
  // prevent.
  for (const statement of ['CREATE DATABASE', 'USE ']) {
    const stillThere = text
      .split('\n')
      .some((line) => line.toUpperCase().startsWith(statement))
    if (stillThere) {
      throw new Error(`${source}: a leading "${statement.trim()}" survived — check the file by hand`)
    }
  }

  const destination = join(outputDir, source)
  writeFileSync(destination, header(source) + text)
  console.log(`${source.padEnd(11)} -> database/railway/${source}`)
}

console.log('\nImport these against the database the host gave you, in this order:')
console.log('  schema.sql, then seed.sql')
